import asyncio

from grpclib.client import Channel

# generated by protoc
from hitchhiker_source_pb2 import DownloadFileRequest, DownloadFileReply
from hitchhiker_source_grpc import HitchhikerSourceStub


async def main():
    async with Channel('127.0.0.1', 3001) as channel:
        hitchhiker = HitchhikerSourceStub(channel)

        reply = await hitchhiker.DownloadFile(DownloadFileRequest(client_id='clientid_1', file_list=[{"file_id": "file_id_1", "file_name": "file_name_1"}, {"file_id": "file_id_2", "file_name": "file_name_2"}]))
        print(reply.files)

if __name__ == '__main__':
    asyncio.run(main())